name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    env:
      IDENTIFICACAO_ALUNO: aluno99
      DIRETORIO_WEBAPP: ./SiteContagem

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301

    - name: Build com o utilitario dotnet
      run: dotnet build ${{ env.DIRETORIO_WEBAPP }} --configuration Release

    - name: Publish com o utilitario dotnet
      run: dotnet publish ${{ env.DIRETORIO_WEBAPP }} -c Release -o app
